baseURL = "https://recambios-aspirador.com/"
canonifyURLs = false
enableRobotsTXT = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
