baseURL = "https://recambios-aspirador.COM/"
languageCode = "es-es"
title = "recambios-aspirador"


enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
amazonTag = ""        # ejemplo: "tutag-21"
aliexpressPid = ""    # lo rellenas cuando te aprueben (PID / tracking id)
